# DeepSeek模型配置示例
model_type: DeepSeek
model: "deepseek-chat"  # DeepSeek模型名称
base_url: "https://api.deepseek.com"  # DeepSeek API端点
api_key: "your-deepseek-api-key-here"  # 替换为真实API密钥

# 系统提示词
system_prompt: "你是一个专业的翻译助手，请将用户提供的文本准确翻译为目标语言。保持原文的语义和语调，确保翻译自然流畅。"

# 目标语言列表
default_languages:
  - en
  - ja
  - fr
  - de
  - ko

# 翻译缓存文件路径
cache_path: output/translations.cache

# 翻译风格：formal(正式) 或 casual(口语化)
translation_style: formal

# API请求频率限制（每分钟请求数）
rate_limit: 10

# 模型参数
temperature: 0.1
max_tokens: 1024